name: Test project

on: [pull_request]

jobs:

  testAllModes:
    name: Test ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - editmode
    steps:
      - uses: actions/checkout@v2
        name: Checkout in ${{ github.ref_name }}
        with:
          lfs: true
      - uses: actions/cache@v2
        name: Caching
        with:
          path: /Library
          key: Library-
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2
        name: Running Tests - ${{ matrix.testMode }}
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2020.3.25f1
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
      - uses: actions/upload-artifact@v2
        name: Uploading Results - ${{ matrix.testMode }}
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
