name: Release

on: [push]

jobs:
  copy-samples-folder:
    name: Copying Samples folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      - run: |
          rm -rf ${{matrix.projectPath}}/Assets/Package/Samples~
          cp -avr ${{matrix.projectPath}}/Assets/Package/Samples ${{matrix.projectPath}}/Assets/Package/Samples~
          git add -all
          git commit -m Creating Samples Folder
